<?php

class IndexController extends Controller
{
	public $data = "";
	public function actionIndex()
	{
		
		
		$info = new Goods();
		$info->uid = 1;
		$info->cat_id = 1000;
		$goods = new GoodsCategory();
		$goods->search($info);
		"http://ninghao.net/blog/494";
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->data  = '{"scrubbedUser": {"is_employee": false, "username": "lengjian", "locale": "en-US", "country": "CN", "autologin": null, "is_partner": true, "id": "377035937462380060"},';
        $this->data .=   '"tree": {
                "resource": null, "name": "App", 
                "children": 
                     		[';
	    $this->data .=  '{"resource": null,  "name": "Header",  "id": "header",  
	                         		"children":[ 
	                            			{"resource": null, "name": "DropdownButton",  "id": "categoriesDropdownButton", "children":[{"resource": null, "name": "Button", "id": "button",  "children": [],  "errorStrategy": 2, "options": { "class_name": "categories", "text": "Categories",  "show_text": false,  "has_icon": true, "primary_on_hover": true }, "uid": "Button-12" }], "errorStrategy": 2, "options": {"class_name": "categoriesButton",  "button_options": {"class_name": "categories", "text": "Categories",  "show_text": false, "has_icon": true, "primary_on_hover": true},  "module": {"resource": {"name": "CategoriesResource", "options": {"browsable": true}}, "name": "CategoriesMenu"}, "dropdown_options": {"largeCaret": true, "fixed": true, "prefetch": true, "view_type": "categoriesMenu"}, "time": 500,"tutorial": {"topic": "categories", "text": "Browse Popular, DIY and other categories to find pins you like.", "title": "Here are your categories."}},"uid": "DropdownButton-7"}, 
				                            {"resource": null, "name": "ui.SearchForm", "id": "mainSearchTextbox","children": [{"resource": null, "name": "ui.TypeaheadField", "id": "searchField", "children": [{"resource": null, "name": "ui.Typeahead", "id": "typeahead", "children": [], "errorStrategy": 2, "options": {"enable_recent_queries": true, "force_empty_state_render": null, "exclude_non_followers": null, "class_name": "inHeader", "view_type": "search", "use_tab_index": null, "num_places": null, "template": null, "tags": "autocomplete"},  "uid": "ui-Typeahead-14"}], "errorStrategy": 2, "options": {"enable_recent_queries": true, "name": "q", "view_type": "search", "class_name": "inHeader", "prefetch_on_focus": true, "value": "", "populate_on_result_highlight": true, "search_delay": 0, "search_on_focus": true, "placeholder": "Search", "tags": "autocomplete"}, "uid": "ui-TypeaheadField-13"}],  "errorStrategy": 2, "options": {"class_name": "inHeader", "enable_recent_queries": true, "navigate_on_search": true, "placeholder": "Search"}, "uid": "ui-SearchForm-8"}, 
				                            {"resource": null, "name": "DropdownButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"has_icon": true, "class_name": "addPinHeader", "show_text": false, "primary_on_hover": true, "text": "Add a Pin"}, "uid": "Button-15"}],  "errorStrategy": 2, "options": {"class_name": "addPinWrapper", "dropdown_options": {"position_point": "BOTTOM_CENTER", "fixed": true, "prefetch": true}, "button_options": {"has_icon": true, "class_name": "addPinHeader", "show_text": false, "text": "Add a Pin", "primary_on_hover": true},  "module": {"name": "AddPin", "options": {"dropdown_style": true}}},  "uid": "DropdownButton-9"}, 
				                            {"resource": {"name": "NotificationsCountResource", "options": {"bookmarks": ["-end-"]}}, "name": "NotificationsButton", "id": "notificationsButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"has_icon": true, "text": "Notifications", "show_text": false, "class_name": "notifs", "primary_on_hover": true}, "uid": "Button-16"}], "errorStrategy": 2, "options": {"dropdown_options": {"position_point": "BOTTOM_RIGHT", "fixed": true, "display_while_loading": true, "view_type": "notificationsDropdown"}, "button_options": {"has_icon": true, "text": "Notifications", "show_text": false, "class_name": "notifs", "primary_on_hover": true}, "tutorial": {"topic": "notifications", "text": "Check the bubble to see your latest Pinterest activity.", "show": false, "title": "New Notifications!"}, "view_type": "merged"}, "uid": "NotificationsButton-10"}, 
				                            {"resource": {"name": "UserResource", "options": {"username": "lengjian"}}, "name": "UserMenu", "id": "userMenu", "extraData": {"userId": "377035937462380060"}, "children": [], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"class_name": "compact", "hide_caret": true, "fixed": true, "prefetch": true, "view_type": "userDropdown"}, "class_name": "userDropdown", "module": {"name": "UserDropdown", "options": {}}, "view_type": "merged"}, "uid": "UserMenu-11"}
				                        ], 
	                            	"errorStrategy": 2, "options": {"class_name": ""}, "uid": "Header-1"
								}, ';
         $this->data .=  '{"resource": null, "name": "ScrollToTop", "id": "scrollToTop", "children": [], "errorStrategy": 2, "options": {}, "uid": "ScrollToTop-2"}, ';
         $this->data .=  '{"resource": null, "name": "Nags", 
                                	"children": [
                                             {"resource": null, "name": "NagBase", "extraData": {"type": "upgrade_ie"}, "children": [{"resource": null, "name": "Button", "children": [], "errorStrategy": 2, "options": {"class_name": "nagClose", "borderless": true}, "uid": "Button-18"}], "errorStrategy": 2, "data": {}, "options": {"can_close": true}, "uid": "NagBase-17"}], 
                                	"errorStrategy": 2, "options": {}, "uid": "Nags-3"
									}, ' ;
           $this->data .=  '
           					{"resource": null, "name": "HomePage", "id": "mainModule", 
                            	"children": [{"resource": {"name": "UserResource", "options": {"username": "lengjian", "field_set_key": "homefeed", "bookmarks": ["-end-"]}}, "name": "AuthHomePage", "id": "authHome", "extraData": {"emptyFeed": false}, 
                            		"children": [{"resource": {"name": "UserHomefeedResource", "options": {"bookmarks": ["Pz8yLT0tMTAyMzg2NTkxNTAyMjQ1MDIyXzEzODM5MTE2OTEsMS09LTI5ODkyNjQ5Mzk4ODMwOTY2N18xMzg0MjU3NTkyfDM2NWZhY2ZlMWM3ZTcxN2E3NzYyNGNhOWMzMmNkNzJiNmJmYmQ2YmQ2NDU4YjE0NWQ2YjY4OTI5YzdhYWIwODU="]}}, "name": "Grid", "id": "feedGrid", 
                            			"children": [{
                            					"resource": {"name": "UserHomefeedResource", "options": {"bookmarks": ["Pz8yLT0tMTAyMzg2NTkxNTAyMjQ1MDIyXzEzODM5MTE2OTEsMS09LTI5ODkyNjQ5Mzk4ODMwOTY2N18xMzg0MjU3NTkyfDM2NWZhY2ZlMWM3ZTcxN2E3NzYyNGNhOWMzMmNkNzJiNmJmYmQ2YmQ2NDU4YjE0NWQ2YjY4OTI5YzdhYWIwODU="]}},
                            					"name": "GridItems", 
                            					"id": "items", 
                            					"children": 
                            							';
            $this->data .=                	   '[{"resource": null, "name": "UserNews", "children": [{"resource": {"name": "UserFriendSuggestionsResource", "options": {"bookmarks": ["-end-"], "min_public_pins": 10}}, "name": "FriendsToFollow", "extraData": {"friendIdsUsed": []}, "children": [], "errorStrategy": 2, "options": {}, "uid": "FriendsToFollow-49"}], "errorStrategy": 2, "options": {"anchored": true}, "uid": "UserNews-23"}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "66498531971855569"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "66498531971855569", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-50"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-53"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/66498531971855569\/", "object_description": "sooo fluffy!", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/2f\/27\/ea\/2f27ea088d791326a7d724fd645b75b6.jpg", "object_id": "66498531971855569"}}}, "uid": "DropdownButton-51"}, 
								                           	 	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "66498531971855569", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-52"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/themetapicture.com\/i-totally-would\/", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/2f\/27\/ea\/2f27ea088d791326a7d724fd645b75b6.jpg", "width": 520, "height": 578}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/2f\/27\/ea\/2f27ea088d791326a7d724fd645b75b6.jpg", "width": 236, "height": 262}, "orig": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/2f\/27\/ea\/2f27ea088d791326a7d724fd645b75b6.jpg", "width": 520, "height": 578}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "66498531971855569", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-24"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "66498531971855499"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "66498531971855499", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-54"}, 
								                           		{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-57"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/66498531971855499\/", "object_description": "Chocolate Coconut Almond Butter Recipe - Almond Joy Butter - #almondbutter #almondjoy - wonkywonderful.com", "object_image_url": "http:\/\/media-cache-cd0.pinimg.com\/236x\/9a\/4b\/ff\/9a4bff62a61fc61d954c3d8f4b47b087.jpg", "object_id": "66498531971855499"}}}, "uid": "DropdownButton-55"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "66498531971855499", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-56"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/wonkywonderful.com\/1\/post\/2013\/10\/chocolate-coconut-almond-butter-recipe.html", "images": {"736x": {"url": "http:\/\/media-cache-cd0.pinimg.com\/736x\/9a\/4b\/ff\/9a4bff62a61fc61d954c3d8f4b47b087.jpg", "width": 610, "height": 750}, "originals": {"url": "http:\/\/media-cache-cd0.pinimg.com\/originals\/9a\/4b\/ff\/9a4bff62a61fc61d954c3d8f4b47b087.jpg", "width": 610, "height": 750}, "236x": {"url": "http:\/\/media-cache-cd0.pinimg.com\/236x\/9a\/4b\/ff\/9a4bff62a61fc61d954c3d8f4b47b087.jpg", "width": 236, "height": 290}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "66498531971855499", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-25"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742567"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742567", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-58"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-61"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742567\/", "object_description": "\"Fiona\" by robertagi on Polyvore", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/77\/6a\/d7\/776ad7772425508658c3c0985a3fbc15.jpg", "object_id": "1477812351742567"}}}, "uid": "DropdownButton-59"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742567", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-60"}], "errorStrategy": 2, "data": {"attribution": {"title": "Fiona", "url": "http:\/\/www.polyvore.com\/fiona\/set?.svc=oembed&id=103618252", "provider_icon_url": "http:\/\/passets-cd.pinterest.com\/images\/api\/attrib\/polyvore@2x.png", "author_name": "robertagi", "provider_favicon_url": "http:\/\/passets-ec.pinterest.com\/images\/api\/attrib\/polyvore.png", "author_url": "http:\/\/robertagi.polyvore.com\/", "provider_name": "polyvore"}, "is_playable": false, "link": "http:\/\/robertagi.polyvore.com\/fiona\/set?.svc=copypaste&embedder=2961448&id=103618252", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/77\/6a\/d7\/776ad7772425508658c3c0985a3fbc15.jpg", "width": 600, "height": 600}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/77\/6a\/d7\/776ad7772425508658c3c0985a3fbc15.jpg", "width": 600, "height": 600}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/77\/6a\/d7\/776ad7772425508658c3c0985a3fbc15.jpg", "width": 236, "height": 236}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742567", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-26"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742566"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742566", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-62"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-65"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742566\/", "object_description": "love this long-sleeved", "object_image_url": "http:\/\/media-cache-ak0.pinimg.com\/236x\/5c\/3b\/94\/5c3b94e9957fe33e008a3dce06e9a6f0.jpg", "object_id": "1477812351742566"}}}, "uid": "DropdownButton-63"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742566", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-64"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/www.stackdealz.com\/deals\/Boohoo-com-Coupon-Codes-and-Discounts--\/", "images": {"736x": {"url": "http:\/\/media-cache-ak0.pinimg.com\/736x\/5c\/3b\/94\/5c3b94e9957fe33e008a3dce06e9a6f0.jpg", "width": 236, "height": 354}, "originals": {"url": "http:\/\/media-cache-ak0.pinimg.com\/originals\/5c\/3b\/94\/5c3b94e9957fe33e008a3dce06e9a6f0.jpg", "width": 236, "height": 354}, "236x": {"url": "http:\/\/media-cache-ak0.pinimg.com\/236x\/5c\/3b\/94\/5c3b94e9957fe33e008a3dce06e9a6f0.jpg", "width": 236, "height": 354}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742566", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-27"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742564"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742564", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-66"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-69"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742564\/", "object_description": "Sequins Top", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/4f\/7c\/7d\/4f7c7dfcbc34ed5b0472c6aafecfdbd1.jpg", "object_id": "1477812351742564"}}}, "uid": "DropdownButton-67"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742564", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-68"}], "errorStrategy": 2, "data": {"attribution": {"title": "Sequins Top", "url": "http:\/\/www.polyvore.com\/sequins_top\/set?.svc=oembed&id=103583009", "provider_icon_url": "http:\/\/passets-cd.pinterest.com\/images\/api\/attrib\/polyvore@2x.png", "author_name": "cindycook10", "provider_favicon_url": "http:\/\/passets-ec.pinterest.com\/images\/api\/attrib\/polyvore.png", "author_url": "http:\/\/cindycook10.polyvore.com\/", "provider_name": "polyvore"}, "is_playable": false, "link": "http:\/\/www.polyvore.com\/m\/set?.embedder=3317453&.svc=pinterest&id=103583009", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/4f\/7c\/7d\/4f7c7dfcbc34ed5b0472c6aafecfdbd1.jpg", "width": 600, "height": 600}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/4f\/7c\/7d\/4f7c7dfcbc34ed5b0472c6aafecfdbd1.jpg", "width": 600, "height": 600}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/4f\/7c\/7d\/4f7c7dfcbc34ed5b0472c6aafecfdbd1.jpg", "width": 236, "height": 236}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742564", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-28"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742560"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742560", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-70"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-73"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742560\/", "object_description": "Profile image of Leigh Anne Connett", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/a8\/00\/e4\/a800e494eaac3156dccf2243b181c9cc.jpg", "object_id": "1477812351742560"}}}, "uid": "DropdownButton-71"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742560", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-72"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/www.f-fashion-gallery.com\/?p=7329\/", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/a8\/00\/e4\/a800e494eaac3156dccf2243b181c9cc.jpg", "width": 600, "height": 600}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/a8\/00\/e4\/a800e494eaac3156dccf2243b181c9cc.jpg", "width": 600, "height": 600}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/a8\/00\/e4\/a800e494eaac3156dccf2243b181c9cc.jpg", "width": 236, "height": 236}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742560", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-29"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742556"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742556", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-74"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-77"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742556\/", "object_description": "\"Fall Winter School Outfit\" by natihasi on Polyvore", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/19\/eb\/a8\/19eba8b91243d22cdeb31f8d2676249d.jpg", "object_id": "1477812351742556"}}}, "uid": "DropdownButton-75"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742556", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-76"}], "errorStrategy": 2, "data": {"attribution": {"title": "Fall Winter School Outfit", "url": "http:\/\/www.polyvore.com\/fall_winter_school_outfit\/set?.svc=oembed&id=93385698", "provider_icon_url": "http:\/\/passets-cd.pinterest.com\/images\/api\/attrib\/polyvore@2x.png", "author_name": "natihasi", "provider_favicon_url": "http:\/\/passets-ec.pinterest.com\/images\/api\/attrib\/polyvore.png", "author_url": "http:\/\/natihasi.polyvore.com\/", "provider_name": "polyvore"}, "is_playable": false, "link": "http:\/\/natihasi.polyvore.com\/fall_winter_school_outfit\/set?.svc=copypaste&embedder=856964&id=93385698", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/19\/eb\/a8\/19eba8b91243d22cdeb31f8d2676249d.jpg", "width": 600, "height": 600}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/19\/eb\/a8\/19eba8b91243d22cdeb31f8d2676249d.jpg", "width": 600, "height": 600}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/19\/eb\/a8\/19eba8b91243d22cdeb31f8d2676249d.jpg", "width": 236, "height": 236}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742556", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-30"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742553"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742553", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-78"}, 
																{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-81"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742553\/", "object_description": "\"inspired look with brown combat boots\" by perrie-edwards-outfits on Polyvore", "object_image_url": "http:\/\/media-cache-ak0.pinimg.com\/236x\/54\/f5\/cf\/54f5cf1b29472e126526bc735226636e.jpg", "object_id": "1477812351742553"}}}, "uid": "DropdownButton-79"}, 
																{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742553", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-80"}], "errorStrategy": 2, "data": {"attribution": {"title": "inspired look with brown combat boots", "url": "http:\/\/www.polyvore.com\/inspired_look_with_brown_combat\/set?.svc=oembed&id=68815997", "provider_icon_url": "http:\/\/passets-cd.pinterest.com\/images\/api\/attrib\/polyvore@2x.png", "author_name": "perrie-edwards-outfits", "provider_favicon_url": "http:\/\/passets-ec.pinterest.com\/images\/api\/attrib\/polyvore.png", "author_url": "http:\/\/perrie-edwards-outfits.polyvore.com\/", "provider_name": "polyvore"}, "is_playable": false, "link": "http:\/\/perrie-edwards-outfits.polyvore.com\/inspired_look_with_brown_combat\/set?.svc=copypaste&embedder=0&id=68815997", "images": {"736x": {"url": "http:\/\/media-cache-ak0.pinimg.com\/736x\/54\/f5\/cf\/54f5cf1b29472e126526bc735226636e.jpg", "width": 600, "height": 600}, "originals": {"url": "http:\/\/media-cache-ak0.pinimg.com\/originals\/54\/f5\/cf\/54f5cf1b29472e126526bc735226636e.jpg", "width": 600, "height": 600}, "236x": {"url": "http:\/\/media-cache-ak0.pinimg.com\/236x\/54\/f5\/cf\/54f5cf1b29472e126526bc735226636e.jpg", "width": 236, "height": 236}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742553", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-31"
															}, 
															{"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742547"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742547", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-82"}, 
																{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-85"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742547\/", "object_description": "Balmain coated boucl\u00e9 biker jacket", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/43\/6c\/f1\/436cf1b162b74e6f32f0fddabe4a574b.jpg", "object_id": "1477812351742547"}}}, "uid": "DropdownButton-83"}, 
																{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742547", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-84"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/www.net-a-porter.com\/product\/183528", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/43\/6c\/f1\/436cf1b162b74e6f32f0fddabe4a574b.jpg", "width": 736, "height": 1104}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/43\/6c\/f1\/436cf1b162b74e6f32f0fddabe4a574b.jpg", "width": 920, "height": 1380}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/43\/6c\/f1\/436cf1b162b74e6f32f0fddabe4a574b.jpg", "width": 236, "height": 354}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742547", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-32"
															}, 
															{"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "1477812351742518"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "1477812351742518", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-86"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-89"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/1477812351742518\/", "object_description": "\"Mixed Prints: Leopard, Green & Navy Stripes\"", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/71\/57\/9e\/71579e3e2e004528168110eafc0620de.jpg", "object_id": "1477812351742518"}}}, "uid": "DropdownButton-87"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "1477812351742518", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-88"}], "errorStrategy": 2, "data": {"attribution": {"title": "Mixed Prints: Leopard, Green & Navy Stripes", "url": "http:\/\/www.polyvore.com\/mixed_prints_leopard_green_navy\/set?.svc=oembed&id=103589166", "provider_icon_url": "http:\/\/passets-cd.pinterest.com\/images\/api\/attrib\/polyvore@2x.png", "author_name": "steffiestaffie", "provider_favicon_url": "http:\/\/passets-ec.pinterest.com\/images\/api\/attrib\/polyvore.png", "author_url": "http:\/\/steffiestaffie.polyvore.com\/", "provider_name": "polyvore"}, "is_playable": false, "link": "http:\/\/steffiestaffie.polyvore.com\/mixed_prints_leopard_green_navy\/set?.svc=copypaste&embedder=5500014&id=103589166", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/71\/57\/9e\/71579e3e2e004528168110eafc0620de.jpg", "width": 600, "height": 600}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/71\/57\/9e\/71579e3e2e004528168110eafc0620de.jpg", "width": 600, "height": 600}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/71\/57\/9e\/71579e3e2e004528168110eafc0620de.jpg", "width": 236, "height": 236}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "1477812351742518", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-33"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "298926493988309730"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "298926493988309730", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-90"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-93"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/298926493988309730\/", "object_description": "Quicksilver Marvel Art", "object_image_url": "http:\/\/media-cache-cd0.pinimg.com\/236x\/0f\/a9\/58\/0fa9583cf264852254e340bce4a7e354.jpg", "object_id": "298926493988309730"}}}, "uid": "DropdownButton-91"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "298926493988309730", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-92"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/www.marvelcomicheroes.com\/search?updated-min=2011-01-01T00:00:00-08:00&updated-max=2012-01-01T00:00:00-08:00&max-results=50", "images": {"736x": {"url": "http:\/\/media-cache-cd0.pinimg.com\/736x\/0f\/a9\/58\/0fa9583cf264852254e340bce4a7e354.jpg", "width": 625, "height": 900}, "originals": {"url": "http:\/\/media-cache-cd0.pinimg.com\/originals\/0f\/a9\/58\/0fa9583cf264852254e340bce4a7e354.jpg", "width": 625, "height": 900}, "236x": {"url": "http:\/\/media-cache-cd0.pinimg.com\/236x\/0f\/a9\/58\/0fa9583cf264852254e340bce4a7e354.jpg", "width": 236, "height": 339}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "298926493988309730", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-34"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "298926493988309701"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "298926493988309701", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-94"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-97"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/298926493988309701\/", "object_description": "Bruce Timm\u2019s cover for Adventures of Superman #4.", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/30\/e5\/61\/30e561f9a8523d4ff61cc93d22cae25f.jpg", "object_id": "298926493988309701"}}}, "uid": "DropdownButton-95"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "298926493988309701", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-96"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/brianmichaelbendis.tumblr.com\/post\/52094074800", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/30\/e5\/61\/30e561f9a8523d4ff61cc93d22cae25f.jpg", "width": 500, "height": 742}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/30\/e5\/61\/30e561f9a8523d4ff61cc93d22cae25f.jpg", "width": 500, "height": 742}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/30\/e5\/61\/30e561f9a8523d4ff61cc93d22cae25f.jpg", "width": 236, "height": 350}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "298926493988309701", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-35"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "298926493988309700"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "298926493988309700", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-98"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-101"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/298926493988309700\/", "object_description": "Superman Retro by Des Taylor", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/b4\/e5\/56\/b4e556ec21704f73156cb663928fa108.jpg", "object_id": "298926493988309700"}}}, "uid": "DropdownButton-99"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "298926493988309700", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-100"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/fashionnaction.blogspot.com\/", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/b4\/e5\/56\/b4e556ec21704f73156cb663928fa108.jpg", "width": 499, "height": 960}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/b4\/e5\/56\/b4e556ec21704f73156cb663928fa108.jpg", "width": 499, "height": 960}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/b4\/e5\/56\/b4e556ec21704f73156cb663928fa108.jpg", "width": 236, "height": 454}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "298926493988309700", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-36"
															}, 
								                            {"resource": {"name": "PinResource", "options": {"field_set_key": "grid_item", "id": "298926493988309698"}}, "name": "Pin", "children": [{"resource": null, "name": "ShowModalButton", "id": "pinItButton", "children": [], "errorStrategy": 2, "options": {"submodule": {"error_strategy": 0, "resource": {"name": "PinResource", "options": {"id": "298926493988309698", "view_type": "repin"}}, "name": "PinCreate", "options": {"action": "repin", "transparent_modal": false, "default_board_id": null, "is_video": false}}, "primary_on_hover": true, "color": "primary", "text": "Pin it", "extra_options": {}, "log_element_type": 0, "require_auth_params": {"action": "pinit"}, "has_icon": true, "show_text": false, "ga_category": "repin_create", "class_name": "repinSmall", "require_auth": true}, "uid": "ShowModalButton-102"}, 
								                            	{"resource": null, "name": "DropdownButton", "id": "sendPinButton", "children": [{"resource": null, "name": "Button", "id": "button", "children": [], "errorStrategy": 2, "options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "uid": "Button-105"}], "errorStrategy": 2, "data": {}, "options": {"dropdown_options": {"position_point": "BOTTOM_CENTER", "largeCaret": false, "force_in_viewport": true, "display_while_loading": true, "view_type": "gridShare", "manually_close": true, "fixed": false, "class_name": "underneathHeader"}, "class_name": "sendPinGrid", "ga_category": "sendPinDropdown", "button_options": {"class_name": "sendSmall", "has_icon": true, "show_text": true, "text": "Send"}, "module": {"resource": {"name": "RecentContactsResource", "options": {"field_set_key": "default"}}, "name": "SendPin", "options": {"object_url": "\/pin\/298926493988309698\/", "object_description": "Classic Lois Lane and Superman by\u00a0Des Taylor", "object_image_url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/e7\/c2\/bd\/e7c2bd00e1cfe593026617acc99fe644.jpg", "object_id": "298926493988309698"}}}, "uid": "DropdownButton-103"}, 
								                            	{"resource": null, "name": "PinLikeButton", "id": "likeButton", "children": [], "errorStrategy": 2, "options": {"liked": false, "class_name": "likeSmall", "pin_id": "298926493988309698", "has_icon": true, "text": "Like", "show_text": false, "ga_category": "like"}, "uid": "PinLikeButton-104"}], "errorStrategy": 2, "data": {"attribution": null, "is_playable": false, "link": "http:\/\/brianmichaelbendis.tumblr.com\/post\/55351010491", "images": {"736x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/736x\/e7\/c2\/bd\/e7c2bd00e1cfe593026617acc99fe644.jpg", "width": 500, "height": 707}, "originals": {"url": "http:\/\/media-cache-ec0.pinimg.com\/originals\/e7\/c2\/bd\/e7c2bd00e1cfe593026617acc99fe644.jpg", "width": 500, "height": 707}, "236x": {"url": "http:\/\/media-cache-ec0.pinimg.com\/236x\/e7\/c2\/bd\/e7c2bd00e1cfe593026617acc99fe644.jpg", "width": 236, "height": 333}}, "embed": null, "is_video": false}, "options": {"component_type": 0, "marker_number": false, "pin_id": "298926493988309698", "show_board": true, "show_pinner": true, "show_pinned_from": false}, "uid": "Pin-37"
															}, 	                          
														],'; 
		$this->data .= 					'"errorStrategy": 1, "data": {}, "options": {"scrollable": true, "show_grid_footer": true, "centered": true, "reflow_all": true, "virtualize": true, "item_options": {"show_pinner": true, "show_pinned_from": false, "show_board": true}, "layout": "variable_height", "track_item_impressions": true}, "uid": "GridItems-21"
												}, 
			                            		{"resource": null, "name": "GridFooter", "children": [], "errorStrategy": 2, "options": {}, "uid": "GridFooter-22"}
			                            	], 
			                            "errorStrategy": 1, "data": {}, "options": {"scrollable": true, "show_grid_footer": true, "centered": true, "reflow_all": true, "virtualize": true, "item_options": {"show_pinner": true, "show_pinned_from": false, "show_board": true}, "layout": "variable_height", "track_item_impressions": true}, "uid": "Grid-20"
										}], 
										"errorStrategy": 1, "data": {}, "options": {"tab": "following"}, "uid": "AuthHomePage-19"
									}], 
								"errorStrategy": 0, "options": {"tab": "following"}, "uid": "HomePage-4"
							},'; 
        $this->data .=  '{"resource": null, "name": "NagNoScript", "extraData": {"type": "no_script"}, "children": [], "errorStrategy": 2, "options": {}, "uid": "NagNoScript-5"}
                          ], 
                      "deps": ["App", "Header", "ScrollToTop", "Nags", "HomePage", "NagNoScript", "DropdownButton", "ui.SearchForm", "NotificationsButton", "UserMenu", "Button", "ui.TypeaheadField", "ui.Typeahead", "NagBase", "AuthHomePage", "Grid", "GridItems", "GridFooter", "UserNews", "Pin", "FriendsToFollow", "PinBase", "ShowModalButton", "PinLikeButton"], "errorStrategy": 2, "attributes": {"class": "App full Module", "id": "App-6"}, "options": {"module": {"error_strategy": 0, "name": "HomePage", "options": {"tab": "following"}}}, "uid": "App-6"
                   },'; 
        $this->data .= '"canDebug": false, "gaAccountNumbers": ["UA-12967896-7"], "canonicalMainDomain": "www.pinterest.com", "isLoggedIn": true, "videojsSwfUrl": "http:\/\/passets-ak.pinterest.com\/webapp\/style\/app\/desktop\/other\/video-js.f483340d.swf"}';
		$this->layout = false;
		$this->render('index');
	}
	public function actionPage(){
		$num = 10;
		$page = $_GET["page"];
		$data = array();
		if($page < 11){
			for($i=0;$i<$num;$i++)
			{
				$pNum=rand(1,44);
				$data[$i]["img"] = "/images/1 (".$pNum.").jpg";
				$data[$i]["height"] = 0; //无高度值
				$data[$i]["title"] = "时间：".date("Y-m-d H:i:s")."<br />".($i+1)."、WindsWaterFlow(第".$page."页)";
			}
		}
		print_r('<div style="visibility: visible;" class="item ">
<div data-component-type="0" class="PinBase Pin Module summary">
<div class="pinWrapper">
<div class="pinImageActionButtonWrapper">
<div class="repinSendButtonWrapper">
 <button data-element-type="0" type="button" class="rounded ShowModalButton Button primary Module primaryOnHover btn repinSmall">
<em></em>
<span class="accessibilityText">Pin it</span></button>
<div class="sendPinGrid DropdownButton Module">
<button type="button" class="rounded Button Module hasText sendSmall btn">
<em></em>
<span class="buttonText">Send</span>
        </button></div>
                    </div>
        <div class="likeEditButtonWrapper">
        <button data-text-unlike="Unlike" data-element-type="1" data-text-like="Like" type="button" class="rounded PinLikeButton Button Module likeSmall btn">
<em></em>
<span class="accessibilityText">Like</span>
</button>
 </div>                    
<div class="pinHolder">
<a href="http://www.pinterest.com/pin/66498531971861246/" class="pinImageWrapper " style="background: #9b908d;">
 <h4 class="pinDomain">dezeen.com</h4>
 <div class="fadeContainer">
<div class="hoverMask"></div>
<img src="/images/bce069a0fd5f2b0f32c821a8fe4560b5.jpg" class="pinImg fullBleed loaded fade" style="width: 236px;height: 354px;" onload="P.Lazy.onImageLoad(this)" alt="House with an iron staircase by Roberto Murgia and Valentina Ravara">
</div>
            </a>
        </div>
    </div>

                                                                    
                
        <div class="pinMeta ">
                                            <p class="pinDescription">House with an iron staircase by Roberto Murgia and Valentina Ravara</p>
            
                    
            
                    </div>
    
    
    

        
    <div class="pinCredits">
        <a href="http://www.pinterest.com/ekcpics/myhandsomehome/" class="creditItem">
                            <img src="/images/ekcpics_1328842142_30.jpg" class="creditImg" style="">

            
            <span class="creditName">Elissandra</span>
                            <span class="creditTitle">MyHandsomeHome</span>
                    </a>
    </div>
    
    
            </div>
</div>
                
                                    </div>');exit;
	}
	
}